export const PATIENTS = {
  pat_1: {
    id: "pat_1",
    name: "Rahul Chakraborty",
    avatar: "RC",
    age: 42,
    gender: "Male",
    phone: "+880 1712-345678",
    bloodType: "O+",
    allergies: ["Penicillin", "Sulfa drugs"],
    chronicConditions: ["Hypertension", "Type 2 Diabetes"],
    emergencyContact: { name: "Sunita Chakraborty", phone: "+880 1698-112233" },
    isFollowUp: true,
  },
  pat_2: {
    id: "pat_2",
    name: "Fatima Begum",
    avatar: "FB",
    age: 35,
    gender: "Female",
    phone: "+880 1855-667890",
    bloodType: "A+",
    allergies: [],
    chronicConditions: [],
    emergencyContact: { name: "Karim Uddin", phone: "+880 1734-445566" },
    isFollowUp: false,
  },
  pat_3: {
    id: "pat_3",
    name: "Mohammad Hasan",
    avatar: "MH",
    age: 58,
    gender: "Male",
    phone: "+880 1623-112244",
    bloodType: "B+",
    allergies: ["Aspirin"],
    chronicConditions: ["Coronary Artery Disease", "Hyperlipidemia"],
    emergencyContact: { name: "Nasrin Hasan", phone: "+880 1799-887766" },
    isFollowUp: true,
  },
  pat_4: {
    id: "pat_4",
    name: "Priya Das",
    avatar: "PD",
    age: 28,
    gender: "Female",
    phone: "+880 1556-998877",
    bloodType: "AB+",
    allergies: ["Latex"],
    chronicConditions: ["Asthma"],
    emergencyContact: { name: "Ravi Das", phone: "+880 1644-332211" },
    isFollowUp: false,
  },
  pat_5: {
    id: "pat_5",
    name: "Abdul Karim",
    avatar: "AK",
    age: 67,
    gender: "Male",
    phone: "+880 1788-554433",
    bloodType: "O-",
    allergies: ["Codeine", "NSAIDs"],
    chronicConditions: ["COPD", "Hypertension", "Arthritis"],
    emergencyContact: { name: "Salma Begum", phone: "+880 1833-221144" },
    isFollowUp: true,
  },
  pat_6: {
    id: "pat_6",
    name: "Nadia Rahman",
    avatar: "NR",
    age: 31,
    gender: "Female",
    phone: "+880 1945-778899",
    bloodType: "A-",
    allergies: [],
    chronicConditions: ["Migraine"],
    emergencyContact: { name: "Tariq Rahman", phone: "+880 1567-442233" },
    isFollowUp: true,
  },
};

export const PAST_VISITS = {
  pat_1: [
    {
      id: "v101",
      date: "2026-01-15",
      chiefComplaint: "Routine blood sugar & BP monitoring",
      diagnosis: "Hypertension & T2DM — controlled",
      prescription: [
        {
          medicine: "Metformin",
          dose: "500mg",
          frequency: "Twice daily",
          duration: "30 days",
        },
        {
          medicine: "Amlodipine",
          dose: "5mg",
          frequency: "Once daily",
          duration: "30 days",
        },
      ],
      notes: "HbA1c down to 7.2%. Continue current regimen.",
      testReports: ["HbA1c_Jan2026.pdf", "Lipid_Panel_Jan2026.pdf"],
    },
    {
      id: "v102",
      date: "2025-12-10",
      chiefComplaint: "Elevated blood sugar levels",
      diagnosis: "T2DM — poorly controlled",
      prescription: [
        {
          medicine: "Metformin",
          dose: "500mg",
          frequency: "Twice daily",
          duration: "30 days",
        },
        {
          medicine: "Glipizide",
          dose: "5mg",
          frequency: "Once daily",
          duration: "15 days",
        },
      ],
      notes: "Adjusted diet counselling given.",
      testReports: ["HbA1c_Dec2025.pdf"],
    },
  ],
  pat_3: [
    {
      id: "v201",
      date: "2026-01-08",
      chiefComplaint: "Chest tightness on exertion",
      diagnosis: "Stable Angina — mild exacerbation",
      prescription: [
        {
          medicine: "Atorvastatin",
          dose: "40mg",
          frequency: "Once daily",
          duration: "60 days",
        },
        {
          medicine: "Aspirin",
          dose: "81mg",
          frequency: "Once daily",
          duration: "60 days",
        },
        {
          medicine: "Nitroglycerin (sublingual)",
          dose: "0.4mg",
          frequency: "As needed",
          duration: "60 days",
        },
      ],
      notes: "Stress test recommended. Avoid heavy exertion.",
      testReports: ["ECG_Jan2026.pdf", "Cardiac_Enzymes_Jan2026.pdf"],
    },
  ],
  pat_5: [
    {
      id: "v301",
      date: "2026-01-20",
      chiefComplaint: "Increased breathlessness",
      diagnosis: "COPD — moderate exacerbation",
      prescription: [
        {
          medicine: "Salbutamol Inhaler",
          dose: "2 puffs",
          frequency: "Three times daily",
          duration: "14 days",
        },
        {
          medicine: "Fluticasone Inhaler",
          dose: "2 puffs",
          frequency: "Twice daily",
          duration: "30 days",
        },
        {
          medicine: "Prednisolone",
          dose: "30mg",
          frequency: "Once daily",
          duration: "5 days",
        },
      ],
      notes: "Pulmonary function test pending.",
      testReports: ["Chest_XRay_Jan2026.pdf"],
    },
    {
      id: "v302",
      date: "2025-12-05",
      chiefComplaint: "Routine COPD follow-up",
      diagnosis: "COPD — stable",
      prescription: [
        {
          medicine: "Salbutamol Inhaler",
          dose: "2 puffs",
          frequency: "Twice daily",
          duration: "30 days",
        },
      ],
      notes: "Stable. Continue maintenance.",
      testReports: [],
    },
  ],
  pat_6: [
    {
      id: "v401",
      date: "2026-01-22",
      chiefComplaint: "Recurring migraines — 3x/week",
      diagnosis: "Episodic migraine with aura",
      prescription: [
        {
          medicine: "Sumatriptan",
          dose: "50mg",
          frequency: "At onset",
          duration: "30 days",
        },
        {
          medicine: "Topiramate",
          dose: "25mg",
          frequency: "Once daily (evening)",
          duration: "60 days",
        },
      ],
      notes: "Trigger diary recommended.",
      testReports: [],
    },
  ],
};
